### ISSUE TITLE
BroadcastReceiver trying to return result during a non-ordered broadcast

### ISSUE THREAD

**Issue by kaiyan910** [inloop/easygcm#32] opened 2015-05-28 07:55 UTC
I don't know it is because of the SDK updated or what I get this error once the app is first launch

BroadcastReceiver trying to return result during a non-ordered broadcast
    java.lang.RuntimeException: BroadcastReceiver trying to return result during a non-ordered broadcast

And it is wired that I get a empty GCM broadcast on the app first launch

Seems the source is this line in the GcmBroadcastReceiver

setResultCode(Activity.RESULT_OK);

would you please have a look on that ? thanks.

**Comment by DanielNovak** [comment] 2015-06-29 09:00
Probably duplicate of #36 .

**Closed** 2015-07-02 09:48 UTC
Labels: duplicate
